<?php

return [
    'models' => [
        'branches' => [
            'class'       => \App\Models\Branch::class,
            'edit_route'  => 'admin.branches.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>null,'is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
        'brands' => [
            'class'       => \App\Models\Brand::class,
            'edit_route'  => 'admin.brands.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image'],
            'except'      => [],
            'relations'   => [],
        ],
        'categories' => [
            'class'       => \App\Models\Category::class,
            'edit_route'  => 'admin.categories.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner', 'meta_image'],
            'except'      => ['position'],
            'relations'   => [
                // 'children'=> ['type'=>'hasMany','fk'=>'parent_id'],
            ],
        ],
        'field_categories' => [
            'class'       => \App\Models\FieldCategory::class,
            'edit_route'  => 'admin.field-categories.edit',
            'columns'     => ['name'=>null, 'title'=>null, 'slug'=>null, 'status'=>null],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
        'fields' => [
            'class'       => \App\Models\Field::class,
            'edit_route'  => 'admin.fields.edit',
            'columns'     => ['name'=>null, 'title'=>null, 'slug'=>null, 'status'=>null],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
        'intros' => [
            'class'       => \App\Models\Intro::class,
            'edit_route'  => 'admin.intros.edit',
            'columns'     => ['name'=>null, 'title'=>'title', 'slug'=>null,'is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner'],
            'except'      => [],
            'relations'   => [],
        ],
        'post_categories' => [
            'class'       => \App\Models\PostCategory::class,
            'edit_route'  => 'admin.post-categories.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner'],
            'except'      => [],
            'relations'   => [
                // 'children'=> ['type'=>'hasMany','fk'=>'parent_id'],
            ],
        ],
        'posts' => [
            'class'       => \App\Models\Post::class,
            'edit_route'  => 'admin.posts.edit',
            'columns'     => ['name'=>null, 'title'=>'title', 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner', 'meta_image'],
            'except'      => [],
            'relations'   => [],
        ],
        'products' => [
            'class'       => \App\Models\Product::class,
            'edit_route'  => 'admin.products.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'meta_image'],
            'except'      => [],
            'relations'   => [
                'variants' => ['type'=>'hasMany','fk'=>'product_id'],
                // 'specifications' => ['type'=>'belongsToMany'],
                // 'images' => ['type'=>'hasMany','fk'=>'item_id'], // morphMany => không bật mặc định
            ],
        ],
        'project_categories' => [
            'class'       => \App\Models\ProjectCategory::class,
            'edit_route'  => 'admin.project-categories.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner', 'meta_image'],
            'except'      => ['position'],
            'relations'   => [
                // 'children'=> ['type'=>'hasMany','fk'=>'parent_id'],
            ],
        ],
        'projects' => [
            'class'       => \App\Models\Project::class,
            'edit_route'  => 'admin.projects.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner'],
            'except'      => [],
            'relations'   => [],
        ],
        'service_categories' => [
            'class'       => \App\Models\ServiceCategory::class,
            'edit_route'  => 'admin.service_categories.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner'],
            'except'      => [],
            'relations'   => [
                // 'children'=> ['type'=>'hasMany','fk'=>'parent_id'],
            ],
        ],
        'services' => [
            'class'       => \App\Models\Service::class,
            'edit_route'  => 'admin.services.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image', 'banner'],
            'except'      => [],
            'relations'   => [],
        ],
        'slides' => [
            'class'       => \App\Models\Slide::class,
            'edit_route'  => 'admin.slides.edit',
            'columns'     => ['name'=>null, 'title'=>'title', 'slug'=>null,'is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image'],
            'except'      => ['position'],
            'relations'   => [],
        ],
        'tags' => [
            'class'       => \App\Models\Tag::class,
            'edit_route'  => 'admin.tags.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug', 'status'=>null],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
        'teams' => [
            'class'       => \App\Models\Team::class,
            'edit_route'  => 'admin.teams.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>null, 'status'=>null],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image'],
            'except'      => ['position'],
            'relations'   => [],
        ],
        'testimonials' => [
            'class'       => \App\Models\Testimonial::class,
            'edit_route'  => 'admin.testimonials.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>null,'is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => ['image'],
            'except'      => ['position'],
            'relations'   => [],
        ],
        'units' => [
            'class'       => \App\Models\Unit::class,
            'edit_route'  => 'admin.units.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>'slug','is_home'=>'is_home','is_menu'=>'is_menu', 'status'=>'status'],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
        'users' => [
            'class'       => \App\Models\User::class,
            'edit_route'  => 'admin.users.edit',
            'columns'     => ['name'=>'name', 'title'=>null, 'slug'=>null, 'status'=>null],
            'name_suffix' => ' (Bản sao)',
            'files'       => [],
            'except'      => [],
            'relations'   => [],
        ],
    ],
];
